[tool.poetry]
name = "pyroll-zouhar-contact"
version = "2.0.0a1"
description = "Plugin for PyRoll providing the contact area estimation by Zouhar"
authors = [
    "Max Weiner <max.weiner@imf.tu-freiberg.de>",
    "Christoph Renzing <christoph.renzing@imf.tu-freiberg.de>",
]
license = "BSD-3-Clause"
homepage = "https://pyroll-project.github.io/"
repository = "https://github.com/pyroll-project/pyroll-zouhar-contact"
documentation = "https://github.com/pyroll-project/pyroll-zouhar-contact/blob/main/docs/docs.pdf"
packages = [
    { include = "pyroll/zouhar_contact" }
]
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Manufacturing",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pyroll-core = "^2.0.0a"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
